import { chromium } from '@playwright/test';
const base = process.argv[2] ?? 'http://localhost:5199';
const out = process.argv[3] ?? 'docs/design/checkpoints/stage6-merged';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs: string[] = [];
p.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
p.on('pageerror', (e) => errs.push(e.message));
await p.goto(base, { waitUntil: 'networkidle' });
await p.getByTestId('app-layout').waitFor({ timeout: 15000 });
await p.getByRole('button', { name: 'Demo controls' }).click();
await p.getByTestId('load-demo-profile-button').click();
await p.waitForTimeout(1500);
await p.keyboard.press('Escape');
await p.getByRole('button', { name: /dossier|full profile|profile/i }).first().click();
await p.waitForTimeout(1200);
await p.screenshot({ path: `${out}/dossier.png`, fullPage: false });
const sh = await p.evaluate(() => document.documentElement.scrollHeight);
console.log('dossier scrollHeight:', sh, 'errors:', errs.length);
for (const e of errs) console.log('  ERR', e);
await b.close();
